---
title: "drake_specification"
author: "Lukas Huber"
date: "2020-7-31, last update (`r Sys.Date()`)"
output: html_notebook
---

```{r setup}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

```{r}
source("R/packages.R")
source("R/functions.R")
source("R/plan.R")
```

```{r}
make(plan)
```

```{r}
vis_drake_graph(plan)
```

## Mandrake

```{r}
```


```{r}
lookup_cache <- mandrake::load_package_colspec("mandrake")
```

```{r}
cache <- drake::drake_cache()
plan_extracted <- plan %>%
  mandrake::decorate_plan(cache=cache, 
                          lookup_cache = lookup_cache,
                          desc_colname = "desc")
```

```{r}
my_config <- drake_config(plan_extracted)
graph_info <- drake_graph_info(
  my_config, 
  group = "cluster_id", 
  clusters = c("summ", "coef"), 
  build_times = "none",
  on_select_col = "desc")

graph <- render_drake_graph(
  graph_info, 
  on_select = mandrake::embed_event_handler(),
  ncol_legend = 4
  ) 
```

```{r}
graph
```


## Buidling

```{r}
#devtools::document()
```

```{r}
#renv::snapshot()
```

## Version_control

```{r eval=F}
library(gert)
```
```{r eval=F}
git_log()
```
```{r eval=F}
git_status()
```

