# Generated by roxytest: Do not edit by hand!

context("File R/functions_scenario_2.R: @tests")

test_that("Function sample_data() @ L16", {
  expect_equal(nrow(sample_data(tibble(x=c(1,2,3,4,5)))),1)
})

