on:
  push

name: pkgdown

jobs:
  pkgdown:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Install Libraries
        run: |
          brew install harfbuzz fribidi
        shell: bash

      - name: Install dependencies
        run: |
          install.packages("renv")
          renv::restore(rebuild=TRUE, clean=TRUE)
        shell: Rscript {0}

      - name: Install package
        run: R CMD INSTALL .

      - name Git Setup
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          ls -l

      - name: Deploy package
        run: |
          renv::run("pkgdown.R")
        shell: Rscript {0}
